version: '3.5'

services:
  front:
    image: nginx
    container_name: lainquiz_front
    ports:
      - 8088:80
    volumes:
      - .:/var/www:ro
      - ./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /var/www

  engine:
    build: ./docker/engine/
    container_name: lainquiz_engine
    volumes:
      - .:/var/www:rw
      - ./docker/engine/php.ini:/usr/local/php/conf.d/custom.ini:ro